#!/bin/bash
#
# @date   : 2019-10-21 (SOL 320)
# @author : Greg Sainton, IPGP

# Simple shell script to convert LMST date to UTC Date Time
# Based on the program lmst2utc executed in Python

# MARSCONVERTER environement variable must be set 
# in your bash first. This variable must be the directory 
# where to find marsnow, marsnow.py and the python class
# MarsConverter.py

#abort on error
set -e

function usage
{
    echo "usage: lmst2utc -d UTCDate "
    echo "   ";
    echo "  -d | --date              : LMST format date (SSSSTHH:MM:ss:mmmmmm)";
    echo "                                       please add microsecond      )";
    echo "  -h | --help              : This message";
}

function parse_args
{
  # positional args
  args=()

  # named args

   case "$1" in
       -d | --date )                 date="$2";               shift;;
       -h | --help )                 usage;                   exit;; # quit and show usage
       * )                           args+=("$1")             # if no match, add it to the positional args
   esac

  # restore positional args
  set -- "${args[@]}"


  # validate required args
  if [[ -z "${date}" ]]; then
      echo "Invalid arguments"
      usage
      exit;
  fi

}

function run
{
  parse_args "$@"
  if [ -z ${MARSCONVERTER} ]; then echo "MARSCONVERTER is unset"; else python $MARSCONVERTER/lmst2utc.py -d $date; fi
}

run "$@";
